version: '3'

services:
  myDB:
    image: postgres:15.3
    container_name: odonto-stock-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admincreator
      - POSTGRES_PASSWORD=mv222
      - POSTGRES_DB=teeth-stock-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
  
  pdAdmin:
    image: dpage/pgadmin4
    container_name: pgadmin-odonto-stock-db
    restart: always
    depends_on:
      - myDB
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=williner.martin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=mv222
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./pgadmin:/certs/server.cert
      - ./pgadmin:/certs/server.key
      - ./pgadmin:/pgadmin4/servers.json